apiVersion: v1
kind: Service
metadata:
  name: python-app-svc
  namespace: python-efk
spec:
  type: ClusterIP
  ports:
    - targetPort: 5001
      port: 5001  
  selector:
    app: python-app
    
      