apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-fluent-bit
spec:
  capacity:
    # Note: storage capacity is not used by the EFS CSI driver.
    # It is required by the PersistentVolume spec.
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "efs-sc" # storageClassName is not required, see note in the following section.
  claimRef:
    name: pvc-fluent-bit
    namespace: python-efk
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0d65cbc6a9a90af8e