apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-fluent-bit
  namespace: python-efk
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "" # Leave as empty string for static provisioning
  resources:
    requests:
      storage: 5Gi